In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("PokemonData.csv")

In [9]:
df['FormaAlterna'] = df.duplicated('Num', keep='first')

b = df[~df['FormaAlterna']]
b.loc[b.groupby('Generation')['Total'].idxmax(), ['Generation','Name','Total']]

     Generation      Name  Total
162           1    Mewtwo    680
269           2     Lugia    680
425           3  Rayquaza    680
552           4    Arceus    720
706           5  Reshiram    680
792           6   Xerneas    680

In [ ]:
# qui te millors stats a cada generació (amb formes alternes)

In [ ]:
# idxmax() dona la fila amb el Total més alt de cada generació
# loc[...] selecciona aquestes files i només les 3 columnes indicades

In [8]:
df.loc[df.groupby('Generation')['Total'].idxmax(), ['Generation','Name','Total']]

     Generation                     Name  Total
163           1      MewtwoMega Mewtwo X    780
268           2  TyranitarMega Tyranitar    700
426           3    RayquazaMega Rayquaza    780
552           4                   Arceus    720
711           5       KyuremBlack Kyurem    700
796           6      DiancieMega Diancie    700

In [ ]:
# el mateix, sense formes alternes (megas, i tal...)

In [ ]:

b = df[~df['FormaAlterna']]    # "~" nega la condició: ens quedem només amb formes base
b.loc[b.groupby('Generation')['Total'].idxmax(), ['Generation','Name','Total']]